// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nsbrpc.proto

package nsbrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionHeader struct {
	Src                  []byte   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  []byte   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Nonce                []byte   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHeader) Reset()         { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()    {}
func (*TransactionHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_597993d2388274b9, []int{0}
}

func (m *TransactionHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHeader.Unmarshal(m, b)
}
func (m *TransactionHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHeader.Marshal(b, m, deterministic)
}
func (m *TransactionHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHeader.Merge(m, src)
}
func (m *TransactionHeader) XXX_Size() int {
	return xxx_messageInfo_TransactionHeader.Size(m)
}
func (m *TransactionHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHeader proto.InternalMessageInfo

func (m *TransactionHeader) GetSrc() []byte {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *TransactionHeader) GetDst() []byte {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *TransactionHeader) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionHeader) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *TransactionHeader) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type FAPair struct {
	FuncName             string   `protobuf:"bytes,1,opt,name=funcName,proto3" json:"funcName,omitempty"`
	Args                 []byte   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FAPair) Reset()         { *m = FAPair{} }
func (m *FAPair) String() string { return proto.CompactTextString(m) }
func (*FAPair) ProtoMessage()    {}
func (*FAPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_597993d2388274b9, []int{1}
}

func (m *FAPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FAPair.Unmarshal(m, b)
}
func (m *FAPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FAPair.Marshal(b, m, deterministic)
}
func (m *FAPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FAPair.Merge(m, src)
}
func (m *FAPair) XXX_Size() int {
	return xxx_messageInfo_FAPair.Size(m)
}
func (m *FAPair) XXX_DiscardUnknown() {
	xxx_messageInfo_FAPair.DiscardUnknown(m)
}

var xxx_messageInfo_FAPair proto.InternalMessageInfo

func (m *FAPair) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *FAPair) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionHeader)(nil), "nsbrpc.TransactionHeader")
	proto.RegisterType((*FAPair)(nil), "nsbrpc.FAPair")
}

func init() { proto.RegisterFile("nsbrpc.proto", fileDescriptor_597993d2388274b9) }

var fileDescriptor_597993d2388274b9 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x4a, 0x03, 0x41,
	0x10, 0x86, 0x39, 0x93, 0x1c, 0x66, 0x49, 0xa1, 0x8b, 0xc5, 0x22, 0x16, 0x92, 0x4a, 0x44, 0x72,
	0x85, 0x8d, 0xad, 0x29, 0x24, 0x55, 0x94, 0xc4, 0xca, 0x6e, 0x6e, 0x6e, 0x3c, 0x17, 0xcc, 0xec,
	0x31, 0xbb, 0x17, 0xf0, 0x41, 0x7c, 0x5f, 0xd9, 0x59, 0xd1, 0xee, 0xff, 0xbe, 0x81, 0xe1, 0x9f,
	0x31, 0x0b, 0x8e, 0xad, 0x0c, 0xb8, 0x1a, 0x24, 0xa4, 0x60, 0xeb, 0x42, 0xcb, 0xef, 0xca, 0x9c,
	0xbf, 0x0a, 0x70, 0x04, 0x4c, 0x3e, 0xf0, 0x86, 0xa0, 0x23, 0xb1, 0x67, 0x66, 0x12, 0x05, 0x5d,
	0x75, 0x5d, 0xdd, 0x2c, 0x76, 0x39, 0x66, 0xd3, 0xc5, 0xe4, 0x4e, 0x8a, 0xe9, 0x62, 0xb2, 0x17,
	0x66, 0x76, 0x84, 0xcf, 0x91, 0xdc, 0x44, 0x5d, 0x81, 0x6c, 0x39, 0x30, 0x92, 0x9b, 0x16, 0xab,
	0x60, 0xad, 0x99, 0x76, 0x90, 0xc0, 0xcd, 0x54, 0x6a, 0xb6, 0x57, 0x66, 0x1e, 0x7d, 0xcf, 0x90,
	0x46, 0x21, 0x57, 0xeb, 0xe0, 0x5f, 0x2c, 0x1f, 0x4c, 0xfd, 0xf4, 0xf8, 0x02, 0x5e, 0xec, 0xa5,
	0x39, 0x7d, 0x1f, 0x19, 0xb7, 0x70, 0x20, 0x2d, 0x34, 0xdf, 0xfd, 0x71, 0xde, 0x0b, 0xd2, 0xc7,
	0xdf, 0x5a, 0x9a, 0xd7, 0x77, 0x6f, 0xb7, 0xbd, 0x4f, 0x1f, 0x63, 0xbb, 0xc2, 0x70, 0x68, 0x36,
	0x5f, 0x03, 0xc9, 0x9e, 0xe4, 0xe8, 0x91, 0x9e, 0x99, 0x9a, 0xed, 0x7e, 0xdd, 0xf4, 0x32, 0x60,
	0x53, 0xee, 0x6f, 0x6b, 0x7d, 0xc7, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xcc, 0x67,
	0x2b, 0x1e, 0x01, 0x00, 0x00,
}
